config:
  log: console
  #log: syslog
  #log: file
  logfile: log

hosts:
  - address: glasswallsolutions.com
    prot: httpstatus
    httpstatus: 200
  - address: glasswallsolutions.com
    prot: httpstring
    httpstring: Glasswall
  - address: 3.139.22.215
    prot: tcp
    tcpport: 1344
  - address: 3.139.22.215
    prot: icap
    icaptestfile: /function/a.pdf
    icapservice: gw_rebuild
    icaptimeout: 60
