config:
  log: console
  #log: syslog
  #log: file
  logfile: log

hosts:
  - address: 8.8.8.8
    prot: "icmp"
  - address: google.com
    prot: icmp
  - address: google.com
    prot: httpstatus
    httpstatus: 200
  - address: google.com
    prot: httpstring
    httpstring: gdoogle
  - address: 3.139.22.215
    prot: tcp
    tcpport: 1344
    icaptestfile: a.pdf
    icapservice: gw_rebuild
    icaptimeout: 60
  - address: 3.139.22.215
    prot: tcp
    tcpport: 1344